name: MeterVEnv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - flask=2.3.2
  - werkzeug=2.3.7
  - sqlalchemy=2.0.40
  - flask-sqlalchemy=3.1.1
  - flask-login=0.6.3
  - flask-wtf=1.2.2
  - flask-dance=7.0.0
  - flask-migrate=4.1.0
  - authlib=1.5.1
  - python-dotenv=1.1.0