"""Recreate user model

Revision ID: 0ad7a125421c
Revises: ade6ea3428c1
Create Date: 2025-05-13 17:30:49.491281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad7a125421c'
down_revision = 'ade6ea3428c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_entries', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_bill_entries_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')


    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=256), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('bill_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bill_entries_user_id', type_='foreignkey')


    # ### end Alembic commands ###
