"""Add share_group_id to SharedReport

Revision ID: 3e7e1a267ac9
Revises: 1066f0edda30
Create Date: 2025-05-17 20:41:30.296985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7e1a267ac9'
down_revision = '1066f0edda30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_group_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_reports', schema=None) as batch_op:
        batch_op.drop_column('share_group_id')

    # ### end Alembic commands ###
