"""Add role, household_code & household_id to users

Revision ID: ef47aaea44eb
Revises: fdbb89372b3b
Create Date: 2025-05-17 10:22:34.312465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef47aaea44eb'
down_revision = 'fdbb89372b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
        batch_op.add_column(sa.Column('household_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('household_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_users_household_code', ['household_code'])
        batch_op.create_foreign_key('fk_users_household_id', 'households', ['household_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_household_id', type_='foreignkey')
        batch_op.drop_constraint('uq_users_household_code', type_='unique')
        batch_op.drop_column('household_id')
        batch_op.drop_column('household_code')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
