"""Add code column to households

Revision ID: fdbb89372b3b
Revises: 222a4c521beb
Create Date: 2025-05-16 23:52:19.354075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbb89372b3b'
down_revision = '222a4c521beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=8), nullable=False))
        batch_op.create_unique_constraint('uq_households_code', ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_constraint('uq_households_code', type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
